server:
    port: 8082
spring:
    application:
        name: serv2
eureka:
    instance:
        prefer-ip-address: true #注册服务的ip
    client:
        service-url:
            defaultZone: http://127.0.0.1:8004/eureka
        fetch-registry: true
        register-with-eureka: true

logging:
    level:
        com:
            codingapi:
                txlcn: DEBUG